version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=niit
      - MYSQL_ROOT_HOST=%
    command: mysqld --init-file="/docker-entrypoint-initdb.d/schema.sql"
